services:
  - type: web
    name: Online_Grocery_Shop
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Online_Grocery_Shop.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Online_Grocery_Shop.settings
